codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: 30...100
  status:
    project:
      default:
        target: 35%
        threshold: 5%
        if_ci_failed: error
    patch:
      default:
        target: 35%
        threshold: 10%

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "tests/**/*"
  - "**/__pycache__/**"
  - "**/.pytest_cache/**"
  - "**/htmlcov/**"
